// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBVNCSto-g2DSc1bPqJJ1IuYwDEhjQgd9A',
    appId: '1:815460410823:web:7da955bcb03fc630b4e5e2',
    messagingSenderId: '815460410823',
    projectId: 'mobilelato',
    authDomain: 'mobilelato.firebaseapp.com',
    storageBucket: 'mobilelato.appspot.com',
    measurementId: 'G-BLEF50GH02',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCAkzHUcIvZoSDTy42SZrS0Oa-VovHRiqE',
    appId: '1:815460410823:android:978635b09a98b61bb4e5e2',
    messagingSenderId: '815460410823',
    projectId: 'mobilelato',
    storageBucket: 'mobilelato.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDmBEimpKHr-mEVENZrOQqMHw_d_L7kd8w',
    appId: '1:815460410823:ios:bde2a88ef9f8300cb4e5e2',
    messagingSenderId: '815460410823',
    projectId: 'mobilelato',
    storageBucket: 'mobilelato.appspot.com',
    iosBundleId: 'com.example.latihan',
  );
}
